### ISSUE TITLE
Async codingame client

### ISSUE THREAD

**Issue by takos22** [Waz0x/codingame_discord_bot#2]
Hello, 
I'm the maintainer of the `codingame` module and I thought I'd give you some tips:
You could use the asynchronous codingame client with `client = codingame.Client(is_async=True)`, then the calls would be awaited, for example `coc = await client.get_pending_clash_of_code()`.
https://github.com/Waz0x/codingame_discord_bot/blob/6a0118be5aa2d680a18c613b0fc070a682df811c/main.py#L13
In that case, you would need to update the `requirements.txt` to `codingame[async]`.
https://github.com/Waz0x/codingame_discord_bot/blob/6a0118be5aa2d680a18c613b0fc070a682df811c/requirements.txt#L1
Making the client async will make sure that the API calls aren't blocking the other code in the bot, there's a better explanation about blocking code in [discord.py docs](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean).

There are some docs about the async client [here](https://codingame.readthedocs.io/en/latest/user_guide/async.html) and if you need any help you can join the support server at [discord.gg/8HgtN6E](https://discord.gg/8HgtN6E).

**Comment by emneo-dev** [comment]
Thank you for your issue, indeed we did not realize an asynchronous client was available.
A proper fix to that is being worked on right now.
